# Generated by Django 4.2 on 2024-06-08 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_rename_pickup_up_location_schedule_pickup_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackschoolcontract',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.schedule'),
        ),
    ]
