# Generated by Django 5.0.2 on 2024-06-09 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_alter_trackschoolcontract_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='drop_time',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='pick_time',
            field=models.TimeField(default = '00:00:00'),
        ),
        migrations.AddField(
            model_name='trackschoolcontract',
            name='cont',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.schoolcontract'),
        ),
    ]
