# Generated by Django 5.0.2 on 2024-06-09 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_alter_schedule_drop_time_alter_schedule_pick_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackschoolcontract',
            name='cont',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.schoolcontract'),
        ),
    ]
