# Generated by Django 5.0.2 on 2024-06-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_alter_trackschoolcontract_cont'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='drop_time',
            field=models.TimeField(default='00:00:00', null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='pick_time',
            field=models.TimeField(default='00:00:00', null=True),
        ),
    ]
