# Generated by Django 5.0.2 on 2024-06-14 10:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_alter_schedule_school_alter_trackschoolcontract_cont_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('pickup_location', models.CharField(max_length=100)),
                ('vias', models.CharField(max_length=100)),
                ('drop_location', models.CharField(max_length=100)),
                ('pick_time', models.TimeField(default='00:00:00', null=True)),
                ('drop_time', models.TimeField(default='00:00:00', null=True)),
                ('price', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.schedule')),
            ],
        ),
    ]
