# Generated by Django 5.0.2 on 2024-06-14 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_inschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='inschedule',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.schoolcontract'),
        ),
    ]
