# Generated by Django 5.0.2 on 2024-06-14 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_inschedule_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackschoolcontract',
            name='sub_Schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.inschedule'),
        ),
    ]
